POST http://localhost:8080/create_event
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNoYW1pbTFAZ21haWwuY29tIiwiZXhwIjoxNzQ2MTk2NTk5LCJ1c2VySWQiOjF9.AAYda3vCUd08quVX_aWidOpXZPkGLtl_0T98IRefP6g

{
    "name": "Quran quiz",
    "description": "To learn quran",
    "location": "japan,tokyo",
    "date": "2025-01-01T15:30:00.000Z"
}