DELETE http://localhost:8080/events/28
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNoYW1pbTJAZ21haWwuY29tIiwiZXhwIjoxNzQ2MTg1MDU1LCJ1c2VySWQiOjR9.UIatykMJtuGRo128PfKVr-m8gF2IfwG5BFcIS8sI45c