PUT http://localhost:8080/update_event/1
Content-Type: application/json

{
    "name": "test",
    "email": "shamim2@gmail.com",
    "location": "japan,tokyo",
    "date": "2025-01-01T15:30:00.000Z"
}